
default_param_dicts = {
    "mnist": {
        "dataset": ["mnist"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [10],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [False], # ** Cuda was set to False ** 
    },
    "famnist": {
        "dataset": ["famnist"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [10],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [False], # ** Cuda was set to False ** 
    },
    "cifar10": {
        "dataset": ["cifar10"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [10],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [False], # ** Cuda was set to False ** 
    },
    "cifar100": {
        "dataset": ["cifar100"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [100],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [False], # ** Cuda was set to False ** 
    },
    "tumor4": {
        "dataset": ["tumor4"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [4],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [False], # ** Cuda was set to False ** 
    },
    "tumor2": {
        "dataset": ["tumor2"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [2],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [False], # ** Cuda was set to False ** 
    },
    "DAC": {
        "dataset": ["Behavioral"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [195],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [False], # ** Cuda was set to False ** 
    },
}
